// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartTracker.Models;

#nullable disable

namespace PartTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127112739_parts_in_transit")]
    partial class parts_in_transit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PartTracker.Models.PartsInTransit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtNr")
                        .HasColumnType("int")
                        .HasColumnName("art_nr");

                    b.Property<int>("AviArtan")
                        .HasColumnType("int")
                        .HasColumnName("avi_artan");

                    b.Property<DateTime?>("AviTid")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("avi_tid");

                    b.Property<DateTime>("AvsDat")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("avs_dat");

                    b.Property<int>("FavArtan")
                        .HasColumnType("int")
                        .HasColumnName("fav_artan");

                    b.Property<DateTime?>("FavTid")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fav_tid");

                    b.Property<int>("FsNr")
                        .HasColumnType("int")
                        .HasColumnName("fs_nr");

                    b.Property<string>("LevNr")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("lev_nr");

                    b.Property<int>("MotAntal")
                        .HasColumnType("int")
                        .HasColumnName("mot_antal");

                    b.Property<DateTime?>("MotTid")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("mot_tid");

                    b.Property<int>("PlanPkt")
                        .HasColumnType("int")
                        .HasColumnName("plan_pkt");

                    b.HasKey("Id")
                        .HasName("p_k_parts_in_transit");

                    b.ToTable("parts_in_transit");
                });
#pragma warning restore 612, 618
        }
    }
}
