// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartTracker.Models;

#nullable disable

namespace PartTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210111531_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PartTracker.Models.ActivityForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("collected_by");

                    b.Property<string>("CollectionType")
                        .HasColumnType("longtext")
                        .HasColumnName("collection_type");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<string>("Comment1")
                        .HasColumnType("longtext")
                        .HasColumnName("comment1");

                    b.Property<string>("Comment2")
                        .HasColumnType("longtext")
                        .HasColumnName("comment2");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completion_time");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Language")
                        .HasColumnType("longtext")
                        .HasColumnName("language");

                    b.Property<string>("MfgCode")
                        .HasColumnType("longtext")
                        .HasColumnName("mfg_code");

                    b.Property<string>("MfgCode1")
                        .HasColumnType("longtext")
                        .HasColumnName("mfg_code1");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PN")
                        .HasColumnType("longtext")
                        .HasColumnName("p_n");

                    b.Property<string>("PartNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("part_number");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Reasons")
                        .HasColumnType("longtext")
                        .HasColumnName("reasons");

                    b.Property<string>("Reasons1")
                        .HasColumnType("longtext")
                        .HasColumnName("reasons1");

                    b.Property<string>("Reasons2")
                        .HasColumnType("longtext")
                        .HasColumnName("reasons2");

                    b.Property<string>("Reasons3")
                        .HasColumnType("longtext")
                        .HasColumnName("reasons3");

                    b.Property<string>("ShpCode")
                        .HasColumnType("longtext")
                        .HasColumnName("shp_code");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("TONumber")
                        .HasColumnType("longtext")
                        .HasColumnName("t_o_number");

                    b.Property<string>("TONumber1")
                        .HasColumnType("longtext")
                        .HasColumnName("t_o_number1");

                    b.HasKey("Id")
                        .HasName("p_k_activity_forms");

                    b.ToTable("activity_forms");
                });

            modelBuilder.Entity("PartTracker.Models.ChangeLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("collected_by");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<string>("Comment1")
                        .HasColumnType("longtext")
                        .HasColumnName("comment1");

                    b.Property<string>("Comment2")
                        .HasColumnType("longtext")
                        .HasColumnName("comment2");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completion_time");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("cost");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("ExcelId")
                        .HasColumnType("longtext")
                        .HasColumnName("excel_id");

                    b.Property<string>("Language")
                        .HasColumnType("longtext")
                        .HasColumnName("language");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<string>("MfgCode")
                        .HasColumnType("longtext")
                        .HasColumnName("mfg_code");

                    b.Property<string>("MfgCode1")
                        .HasColumnType("longtext")
                        .HasColumnName("mfg_code1");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PartNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("part_number");

                    b.Property<string>("Pn")
                        .HasColumnType("longtext")
                        .HasColumnName("pn");

                    b.Property<string>("PremiumBooking")
                        .HasColumnType("longtext")
                        .HasColumnName("premium_booking");

                    b.Property<string>("Quantity")
                        .HasColumnType("longtext")
                        .HasColumnName("quantity");

                    b.Property<string>("Reasons")
                        .HasColumnType("longtext")
                        .HasColumnName("reasons");

                    b.Property<string>("Reasons1")
                        .HasColumnType("longtext")
                        .HasColumnName("reasons1");

                    b.Property<string>("Reasons2")
                        .HasColumnType("longtext")
                        .HasColumnName("reasons2");

                    b.Property<string>("ShpCode")
                        .HasColumnType("longtext")
                        .HasColumnName("shp_code");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("ToNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("to_number");

                    b.Property<string>("ToNumber1")
                        .HasColumnType("longtext")
                        .HasColumnName("to_number1");

                    b.HasKey("Id")
                        .HasName("p_k_change_log_entries");

                    b.ToTable("change_log_entries");
                });

            modelBuilder.Entity("PartTracker.Models.PartsInTransit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtNr")
                        .HasColumnType("int")
                        .HasColumnName("art_nr");

                    b.Property<int>("AviArtan")
                        .HasColumnType("int")
                        .HasColumnName("avi_artan");

                    b.Property<DateTime?>("AviTid")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("avi_tid");

                    b.Property<DateTime>("AvsDat")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("avs_dat");

                    b.Property<int>("FavArtan")
                        .HasColumnType("int")
                        .HasColumnName("fav_artan");

                    b.Property<DateTime?>("FavTid")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fav_tid");

                    b.Property<int>("FsNr")
                        .HasColumnType("int")
                        .HasColumnName("fs_nr");

                    b.Property<string>("LevNr")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("lev_nr");

                    b.Property<int>("MotAntal")
                        .HasColumnType("int")
                        .HasColumnName("mot_antal");

                    b.Property<DateTime?>("MotTid")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("mot_tid");

                    b.Property<int>("PlanPkt")
                        .HasColumnType("int")
                        .HasColumnName("plan_pkt");

                    b.HasKey("Id")
                        .HasName("p_k_parts_in_transit");

                    b.ToTable("parts_in_transit");
                });

            modelBuilder.Entity("PartTracker.Models.SafetyStockItem", b =>
                {
                    b.Property<string>("PartNumber")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("part_number");

                    b.Property<string>("MfgSupplierCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mfg_supplier_code");

                    b.Property<float>("SafetyStockNrOfParts")
                        .HasColumnType("float")
                        .HasColumnName("safety_stock_nr_of_parts");

                    b.HasKey("PartNumber")
                        .HasName("p_k_safety_stock_items");

                    b.ToTable("safety_stock_items");
                });
#pragma warning restore 612, 618
        }
    }
}
