// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartTracker.Models;

#nullable disable

namespace PartTracker.Migrations.AutomationDb
{
    [DbContext(typeof(AutomationDbContext))]
    [Migration("20260218092542_PremiumBookingUpdate")]
    partial class PremiumBookingUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PartTracker.Models.ActivityForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("CollectionType")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment1")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment2")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("MfgCode")
                        .HasColumnType("longtext");

                    b.Property<string>("MfgCode1")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PN")
                        .HasColumnType("longtext");

                    b.Property<string>("PartNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reasons")
                        .HasColumnType("longtext");

                    b.Property<string>("Reasons1")
                        .HasColumnType("longtext");

                    b.Property<string>("Reasons2")
                        .HasColumnType("longtext");

                    b.Property<string>("Reasons3")
                        .HasColumnType("longtext");

                    b.Property<string>("ShpCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TONumber")
                        .HasColumnType("longtext");

                    b.Property<string>("TONumber1")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("activity", (string)null);
                });

            modelBuilder.Entity("PartTracker.Models.AftermarketCollectionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("CollectedBy");

                    b.Property<string>("Comment1")
                        .HasColumnType("longtext")
                        .HasColumnName("Comment1");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CompletionTime");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("PN")
                        .HasColumnType("longtext")
                        .HasColumnName("PN");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<string>("Reasons1")
                        .HasColumnType("longtext")
                        .HasColumnName("Reasons1");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartTime");

                    b.HasKey("Id");

                    b.ToTable("aftermarketcollection", (string)null);
                });

            modelBuilder.Entity("PartTracker.Models.HelperEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryIdLeft5")
                        .HasColumnType("longtext")
                        .HasColumnName("delivery_id_left5");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("order_number");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("longtext")
                        .HasColumnName("reason_code");

                    b.Property<string>("StatusReadyUser")
                        .HasColumnType("longtext")
                        .HasColumnName("status_ready_user");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("helper", (string)null);
                });

            modelBuilder.Entity("PartTracker.Models.PartPrice", b =>
                {
                    b.Property<string>("PartNumber")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PART_NUMBER");

                    b.Property<decimal>("StandardPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("STANDARD_PRICE");

                    b.HasKey("PartNumber");

                    b.ToTable("Part_Price", (string)null);
                });

            modelBuilder.Entity("PartTracker.Models.Premium2024", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("CarrierBillingName")
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_billing_name");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<string>("ConsignorCountryCode")
                        .HasColumnType("longtext")
                        .HasColumnName("consignor_country_code");

                    b.Property<string>("ConsignorName")
                        .HasColumnType("longtext")
                        .HasColumnName("consignor_name");

                    b.Property<string>("CurrencyOrg")
                        .HasColumnType("longtext")
                        .HasColumnName("currency_org");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("DeliveryName")
                        .HasColumnType("longtext")
                        .HasColumnName("delivery_name");

                    b.Property<long?>("LoadNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("loadnumber");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("longtext")
                        .HasColumnName("reason_code");

                    b.Property<string>("RecipientCountryCode")
                        .HasColumnType("longtext")
                        .HasColumnName("recipient_country_code");

                    b.Property<string>("RecipientName")
                        .HasColumnType("longtext")
                        .HasColumnName("recipient_name");

                    b.Property<string>("ServiceType")
                        .HasColumnType("longtext")
                        .HasColumnName("service_type");

                    b.Property<long?>("ToNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("to_number");

                    b.Property<decimal?>("TotalCostsOrg")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_costs_org");

                    b.Property<decimal?>("TotalCostsSek")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_costs_sek");

                    b.HasKey("Id");

                    b.ToTable("premiums2024", (string)null);
                });

            modelBuilder.Entity("PartTracker.Models.Premium2025", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarrierBillingName")
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_billing_name");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<string>("ConsignorCountryCode")
                        .HasColumnType("longtext")
                        .HasColumnName("consignor_country_code");

                    b.Property<string>("ConsignorName")
                        .HasColumnType("longtext")
                        .HasColumnName("consignor_name");

                    b.Property<string>("CurrencyOrg")
                        .HasColumnType("longtext")
                        .HasColumnName("currency_org");

                    b.Property<string>("DeliveryName")
                        .HasColumnType("longtext")
                        .HasColumnName("delivery_name");

                    b.Property<string>("LoadNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("load_number");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("longtext")
                        .HasColumnName("reason_code");

                    b.Property<string>("RecipientCountryCode")
                        .HasColumnType("longtext")
                        .HasColumnName("recipient_country_code");

                    b.Property<string>("RecipientName")
                        .HasColumnType("longtext")
                        .HasColumnName("recipient_name");

                    b.Property<string>("ServiceType")
                        .HasColumnType("longtext")
                        .HasColumnName("service_type");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("shipment_date");

                    b.Property<string>("ToNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("to_number");

                    b.Property<decimal?>("TotalCostsOrg")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_costs_org");

                    b.Property<decimal?>("TotalCostsSek")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_costs_sek");

                    b.HasKey("Id");

                    b.ToTable("premiums2025", (string)null);
                });

            modelBuilder.Entity("PartTracker.Models.PremiumBookingUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingType")
                        .HasColumnType("longtext");

                    b.Property<string>("CommentMain")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("MFGCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Reasons")
                        .HasColumnType("longtext");

                    b.Property<string>("SHPCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TONumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("premiumbookingupdate", (string)null);
                });

            modelBuilder.Entity("PartTracker.Models.SafetyStockFormEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ByPnOrMfgCode")
                        .HasColumnType("longtext")
                        .HasColumnName("by_pn_or_mfg_code");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<string>("Comment1")
                        .HasColumnType("longtext")
                        .HasColumnName("comment1");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completion_time");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Language")
                        .HasColumnType("longtext")
                        .HasColumnName("language");

                    b.Property<string>("MfgCode")
                        .HasColumnType("longtext")
                        .HasColumnName("mfg_code");

                    b.Property<string>("MfgCode1")
                        .HasColumnType("longtext")
                        .HasColumnName("mfg_code1");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<decimal?>("NewPouOffsetsShifts")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("new_pou_offsets_shifts");

                    b.Property<decimal?>("NewSafetyStockPerPiece")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("new_safety_stock_per_piece");

                    b.Property<decimal?>("NewSafetyStockPerShift")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("new_safety_stock_per_shift");

                    b.Property<decimal?>("NewSafetyStockPieces")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("new_safety_stock_pieces");

                    b.Property<decimal?>("NewSafetyStockShifts")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("new_safety_stock_shifts");

                    b.Property<decimal?>("OldPouOffsetsShifts")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("old_pou_offsets_shifts");

                    b.Property<decimal?>("OldSafetyStockPerPiece")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("old_safety_stock_per_piece");

                    b.Property<decimal?>("OldSafetyStockPerShift")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("old_safety_stock_per_shift");

                    b.Property<decimal?>("OldSafetyStockPieces")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("old_safety_stock_pieces");

                    b.Property<decimal?>("OldSafetyStockShifts")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("old_safety_stock_shifts");

                    b.Property<string>("PartNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("part_number");

                    b.Property<string>("ShpCode")
                        .HasColumnType("longtext")
                        .HasColumnName("shp_code");

                    b.Property<string>("ShpCode1")
                        .HasColumnType("longtext")
                        .HasColumnName("shp_code1");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.ToTable("safetystockform", (string)null);
                });

            modelBuilder.Entity("PartTracker.Models.SpeedUpModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("CollectedBy");

                    b.Property<string>("Comment2")
                        .HasColumnType("longtext")
                        .HasColumnName("Comment2");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CompletionTime");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<string>("MFGCode1")
                        .HasColumnType("longtext")
                        .HasColumnName("MFGCode1");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("PartNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("PartNumber");

                    b.Property<string>("Reasons2")
                        .HasColumnType("longtext")
                        .HasColumnName("Reasons2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartTime");

                    b.Property<string>("TONumber1")
                        .HasColumnType("longtext")
                        .HasColumnName("TONumber1");

                    b.HasKey("Id");

                    b.ToTable("speedup");
                });

            modelBuilder.Entity("PartTracker.Models.SpeedUpRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedPerson")
                        .HasColumnType("longtext")
                        .HasColumnName("Approved Person");

                    b.Property<string>("CarrierCode")
                        .HasColumnType("longtext")
                        .HasColumnName("Carrier Code");

                    b.Property<decimal?>("ConfirmedCost")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Confirmed Cost (Euro)");

                    b.Property<DateTime?>("ConfirmedFinalETA")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Confirmed Final ETA");

                    b.Property<string>("DeliveryPlant")
                        .HasColumnType("longtext")
                        .HasColumnName("Delivery Plant");

                    b.Property<decimal?>("ExtraCost")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Extra Cost (Euro)");

                    b.Property<string>("IBLWorkingNote")
                        .HasColumnType("longtext")
                        .HasColumnName("IBL Working Note");

                    b.Property<string>("ImpactComment")
                        .HasColumnType("longtext")
                        .HasColumnName("Impact & Comment");

                    b.Property<string>("ItemType")
                        .HasColumnType("longtext")
                        .HasColumnName("Item Type");

                    b.Property<string>("LoadNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("Load Number");

                    b.Property<DateTime?>("LoadOriginalDeliveryFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Load Original Delivery From");

                    b.Property<DateTime?>("LoadOriginalDeliveryTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Load Original Delivery To");

                    b.Property<DateTime?>("LoadOriginalPickupFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Load Original Pickup From");

                    b.Property<DateTime?>("LoadOriginalPickupTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Load Original Pickup To");

                    b.Property<DateTime?>("NewAgreedETA")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("New Agreed ETA");

                    b.Property<DateTime?>("NewDeliveryDeadline")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("New Delivery Deadline");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("longtext")
                        .HasColumnName("Reason Code");

                    b.Property<string>("RequestStatus")
                        .HasColumnType("longtext")
                        .HasColumnName("Request Status");

                    b.Property<string>("Requester")
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("longtext")
                        .HasColumnName("Supplier Code");

                    b.Property<string>("TONumber")
                        .HasColumnType("longtext")
                        .HasColumnName("TO Number");

                    b.HasKey("Id");

                    b.ToTable("ibl_emea_speedup_requests", (string)null);
                });

            modelBuilder.Entity("PartTracker.Models.SplunkEntry", b =>
                {
                    b.Property<string>("LoadNumber")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LoadNumber");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext")
                        .HasColumnName("Currency");

                    b.Property<string>("DeliveryContactPerson")
                        .HasColumnType("longtext")
                        .HasColumnName("DeliveryContactPerson");

                    b.Property<string>("FDP")
                        .HasColumnType("longtext")
                        .HasColumnName("FDP");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("longtext")
                        .HasColumnName("SupplierCode");

                    b.Property<decimal?>("TotalCostEUR")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("TotalCostEUR");

                    b.Property<string>("TransportOrder")
                        .HasColumnType("longtext")
                        .HasColumnName("TransportOrder");

                    b.HasKey("LoadNumber");

                    b.ToTable("splunk", (string)null);
                });

            modelBuilder.Entity("PartTracker.Models.TestCrudSafety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ByPnOrMfgCode")
                        .HasColumnType("longtext")
                        .HasColumnName("by_pn_or_mfg_code");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<string>("Comment1")
                        .HasColumnType("longtext")
                        .HasColumnName("comment1");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completion_time");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Language")
                        .HasColumnType("longtext")
                        .HasColumnName("language");

                    b.Property<string>("MfgCode")
                        .HasColumnType("longtext")
                        .HasColumnName("mfg_code");

                    b.Property<string>("MfgCode1")
                        .HasColumnType("longtext")
                        .HasColumnName("mfg_code1");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<decimal?>("NewPouOffsetsShifts")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("new_pou_offsets_shifts");

                    b.Property<decimal?>("NewSafetyStockPerPiece")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("new_safety_stock_per_piece");

                    b.Property<decimal?>("NewSafetyStockPerShift")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("new_safety_stock_per_shift");

                    b.Property<decimal?>("NewSafetyStockPieces")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("new_safety_stock_pieces");

                    b.Property<decimal?>("NewSafetyStockShifts")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("new_safety_stock_shifts");

                    b.Property<decimal?>("OldPouOffsetsShifts")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("old_pou_offsets_shifts");

                    b.Property<decimal?>("OldSafetyStockPerPiece")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("old_safety_stock_per_piece");

                    b.Property<decimal?>("OldSafetyStockPerShift")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("old_safety_stock_per_shift");

                    b.Property<decimal?>("OldSafetyStockPieces")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("old_safety_stock_pieces");

                    b.Property<decimal?>("OldSafetyStockShifts")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("old_safety_stock_shifts");

                    b.Property<string>("PartNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("part_number");

                    b.Property<string>("ShpCode")
                        .HasColumnType("longtext")
                        .HasColumnName("shp_code");

                    b.Property<string>("ShpCode1")
                        .HasColumnType("longtext")
                        .HasColumnName("shp_code1");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.ToTable("TestCrudSafety", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
